// <auto-generated />
using System;
using EventLogger.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventLogger.Migrations
{
    [DbContext(typeof(EventLoggerDbContext))]
    partial class EventLoggerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("EventLogger.EventLogger.Domain.Entities.EventLog", b =>
                {
                    b.Property<int>("EventLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeEvent")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventLogId");

                    b.ToTable("EventLog", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
